
'''
  Read csv file, copy subclass10 to dir
  Preprocess 512
  Crop optic disc
'''

import sys, os, shutil, uuid
import pandas as pd
from LIBS.DLP.my_dlp_helper import  crop_optic_disc_dir
from LIBS.DataPreprocess.my_compute_digest import CalcSha1

COPY_FILES_FROM_CSV = True
DO_PREPROCESS = True

filename_csv = os.path.abspath(os.path.join(sys.path[0], "..", 'datafiles', 'DLP_SubClass_10.csv'))
dir_original = '/media/ubuntu/data1/multi_labels_2919_1_15/'
dir_preprocess = '/home/ubuntu/multi_labels_2919_1_15/preprocess384/'
dir_dest = '/tmp2/SubClass10/original/'


# operate  csv file(generated by my_gen_subclass_csv.py), copy subclass10 to dir
if COPY_FILES_FROM_CSV:
    df = pd.read_csv(filename_csv)

    for _, row in df.iterrows():
        image_filename = row["images"]
        label = row["labels"]

        image_filename_source = image_filename.replace(dir_preprocess, dir_original)
        _, filename_ext = os.path.splitext(image_filename_source)

        # str_uuid = str(uuid.uuid1())
        # image_filename_dest = os.path.join(dir_dest, '10', str(label), str_uuid+filename_ext)

        sha1 = CalcSha1(image_filename_source)
        image_filename_dest = os.path.join(dir_dest, '10', str(label), sha1+filename_ext)

        if not os.path.exists(os.path.dirname(image_filename_dest)):
            os.makedirs(os.path.dirname(image_filename_dest))

        shutil.copy(image_filename_source, image_filename_dest)

        print(image_filename_dest)

    print('read csv file, copy subclass10 to dir OK!')


#region preprocess 512

# dir_original = '/tmp2/SubClass10/original/'
dir_original = dir_dest
dir_preprocess512 = '/tmp2/SubClass10/preprocess512/'

if DO_PREPROCESS:
    from LIBS.ImgPreprocess.my_preprocess_dir import do_process_dir
    do_process_dir(dir_original, dir_preprocess512, image_size=512)
    print('preprocess OK!')

#endregion

#region crop optic disc 112

dir_source = dir_preprocess512
dir_dest = '/tmp2/SubClass10_new/Crop_optic_disc_112/'

crop_optic_disc_dir(dir_source=dir_source, dir_dest=dir_dest, server_port=21000, mask=True)

print('crop optic disc 112 OK!')

#endregion

print('OK')